# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord highlight.js
# Repository: https://github.com/arcticicestudio/nord-highlightjs
# License:    MIT
# References:
#   https://docs.travis-ci.com/user/languages/javascript-with-nodejs

language: node_js
dist: trusty
sudo: false
node_js:
  - "6"
  - "8"
os:
  - linux
  - osx
before_install:
  - rm -rf ./node_modules
before_script:
  - npm install -g gulp-cli
  - npm install gulp
  - npm install
script: gulp --harmony lint
