# Copyright (C) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (C) 2017-present Sven Greb <development@svengreb.de>
#
# Project:    Nord highlight.js
# Repository: https://github.com/arcticicestudio/nord-highlightjs
# License:    MIT
#
# References:
#   https://circleci.com/docs
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7
    steps:
      - checkout
      - run:
          name: install-global-gulp-cli
          command: sudo npm install -g gulp-cli
      - run:
          name: npm-install
          command: npm install
      - run:
          name: lint
          command: gulp --harmony lint
